apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: storagebs-manager
  name: storagebs-manager
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: storagebs-manager
  template:
    metadata:
      labels:
        app: storagebs-manager
    spec:
      initContainers:
      - name: install
        image: registry.cn-hangzhou.aliyuncs.com/link-cloud/initcubepaas-bs:v0.5.0
        imagePullPolicy: Always
        command: ["/bin/sh","-c","/home/init.sh && ls /usr/sbin/iscsi*"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: iscsiusr
          mountPath: /usr/sbin/
        - name: proc
          mountPath: /host/proc/
        - name: tmp
          mountPath: /tmp/ 
      containers:
      - name: storagebs-manager
        image: "{{ .Values.image.longhorn.manager }}:{{ .Values.image.longhorn.managerTag }}"
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - "{{ .Values.image.longhorn.engine }}:{{ .Values.image.longhorn.engineTag }}"
        - --manager-image
        - "{{ .Values.image.longhorn.manager }}:{{ .Values.image.longhorn.managerTag }}"
        - --service-account
        - longhorn-service-account
        ports:
        - containerPort: 9500
          name: manager
        resources:
          limits:
            cpu: {{ .Values.resources.manager.limits.cpu }}
            memory: {{ .Values.resources.manager.limits.memory }}
          requests:
            cpu: {{ .Values.resources.manager.requests.cpu }}
            memory: {{ .Values.resources.manager.requests.cpu }}
        volumeMounts:
        - name: dev
          mountPath: /host/dev/
        - name: proc
          mountPath: /host/proc/
        - name: varrun
          mountPath: /var/run/
        - name: longhorn
          mountPath: /var/lib/rancher/longhorn/
          mountPropagation: Bidirectional
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LONGHORN_BACKEND_SVC
          value: storagebs-backend
      volumes:
      - name: tmp
        hostPath:
          path: /tmp/
      - name: iscsiusr
        hostPath:
          path: /usr/sbin/
      - name: dev
        hostPath:
          path: /dev/
      - name: proc
        hostPath:
          path: /proc/
      - name: varrun
        hostPath:
          path: /var/run/
      - name: longhorn
        hostPath:
          path: /var/lib/rancher/longhorn/
      serviceAccountName: longhorn-service-account
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: storagebs-manager
  name: storagebs-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.manager.type }}
  sessionAffinity: ClientIP
  selector:
    app: storagebs-manager
  ports:
  - name: manager
    port: 9500
    targetPort: manager
    {{- if .Values.service.manager.nodePort }}
    nodePort: {{ .Values.service.manager.nodePort }}
    {{- end }}
