dependencies:
  - name: elasticsearch
    version: 0.0.1
    condition: elasticsearch.enabled
    repository: "file://./charts/elasticsearch/"

  - name: filebeat
    version: 0.0.1
    condition: filebeat.enabled
    repository: "file://./charts/filebeat/"
  
  - name: reloader
    version: 0.0.1
    repository: "file://./charts/reloader/"
