apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test
  name: test-elasticsearch
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test
    spec:
      containers:
      - image: elasticsearch:7.3.0
        name: test-elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300