apiVersion: v1
name: cubedbs
version: 0.5.0
appVersion: v0.5.0
kubeVersion: ">=v1.8.0-r0"
description: cubedbs is a distributed block storage system for Kubernetes
keywords:
- cubedbs
- storage
- distributed
- block
- device
- iscsi
