---
# Source: reloader/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reloader
    chart: "reloader-v0.0.40"
    release: "v0.0.40"
    heritage: "Tiller"
    group: com.stakater.platform
    provider: stakater
    version: v0.0.40
    
  name: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
      release: "v0.0.40"
  template:
    metadata:
      labels:
        app: reloader
        chart: "reloader-v0.0.40"
        release: "v0.0.40"
        heritage: "Tiller"
        group: com.stakater.platform
        provider: stakater
        version: v0.0.40
        
    spec:
      containers:
      - env:
        image: "stakater/reloader:v0.0.40"
        imagePullPolicy: IfNotPresent
        name: reloader
        args:
      serviceAccountName: {{ template "serviceAccount" . }}

